export const drug = [
  {
    value: "resuscitation",
    label: "Resuscitation",
    min: 1,
    max: 2,
    coef: 1,
    unit: "ml",
  },
  {
    value: "adenosine",
    label: "Adenosine",
    min: 0,
    max: 12,
    coef: 6,
    unit: "ml",
  },
  {
    value: "adrenaline",
    label: "Adrenaline",
    min: 0,
    max: 1,
    coef: 0.1,
    unit: "ml",
  },
  {
    value: "atropineSulfate",
    label: "Atropine Sulfate",
    min: 0.1,
    max: 3,
    coef: 0.5,
    unit: "ml",
  },
  {
    value: "calciumGluconate",
    label: "10 % Calcium Gluconate",
    min: 0,
    max: 10,
    coef: 1,
    unit: "ml",
  },
  {
    value: "amiodarone",
    label: "Cordarone (Amiodarone)",
    min: 0,
    max: 150,
    coef: 15,
    unit: "ml",
  },
  {
    value: "glucose",
    label: "Magnesium Sulfate",
    min: 0,
    max: 50,
    coef: 5,
    unit: "ml",
  },
  { 
    value: "nahco3", 
    label: "NaHCO3", 
    min: 0, 
    max: 50, 
    coef: 5, 
    unit: "ml" },
  {
    value: "naloxone",
    label: "Narcan (Naloxone)",
    min: 0,
    max: 2,
    coef: 0.2,
    unit: "ml",
  },
  {
    value: "lidocane",
    label: "Xylocard (Lidocane)",
    min: 0,
    max: 300,
    coef: 30,
    unit: "ml",
  },
];
