import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Menu, Transition } from "@headlessui/react";
import MultiSelectSearchBox from "@/components/multiSelectSearchBox";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-base-200 min-h-screen">
          <div className="navbar bg-base-100 drop-shadow ">
            <div className="navbar-start">
              <div className="dropdown">
                <label tabindex="0" className="btn btn-ghost lg:hidden">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-5 w-5"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M4 6h16M4 12h8m-8 6h16"
                    />
                  </svg>
                </label>
                <ul
                  tabindex="0"
                  className="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52"
                >
                  <li>
                    <a>Item 1</a>
                  </li>
                  <li tabindex="0">
                    <a className="justify-between">
                      Parent
                      <svg
                        className="fill-current"
                        xmlns="http://www.w3.org/2000/svg"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                      >
                        <path d="M8.59,16.58L13.17,12L8.59,7.41L10,6L16,12L10,18L8.59,16.58Z" />
                      </svg>
                    </a>
                    <ul className="p-2">
                      <li>
                        <a>Submenu 1</a>
                      </li>
                      <li>
                        <a>Submenu 2</a>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <a>Item 3</a>
                  </li>
                </ul>
              </div>{" "}
              {/* dropdown */}
              <a className="btn btn-ghost normal-case text-xl">PointPED</a>
            </div>
            <div className="navbar-center hidden lg:flex">
              <ul className="menu menu-horizontal px-1">
                <li>
                  <a>Item 1</a>
                </li>
                <li tabindex="0">
                  <a>
                    Parent
                    <svg
                      className="fill-current"
                      xmlns="http://www.w3.org/2000/svg"
                      width="20"
                      height="20"
                      viewBox="0 0 24 24"
                    >
                      <path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" />
                    </svg>
                  </a>
                  <ul className="p-2 menu bg-base-100 w-56 p-2 rounded-box">
                    <li>
                      <a>Submenu 1</a>
                    </li>
                    <li>
                      <a>Submenu 2</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <a>Item 3</a>
                </li>
              </ul>
            </div>
            <div className="navbar-end">
              <a className="btn btn-accent">Get started</a>
            </div>
          </div>{" "}
          {/* navbar */}
          
          <div className="mx-3 my-5">
            <div className="container max-w-screen-md mx-auto bg-base-100 text-base-content rounded-lg p-2 drop-shadow-md">
            <div className="prose-lg lg:prose-xl text-center p-3 font-bold">
              <h1>Select Drug</h1>
            </div>
            
              <div className="form-control w-auto px-4">
              <MultiSelectSearchBox/>
                <label className="label">
                  <span className="label-text">What is your name?</span>
                </label>
                <input
                  type="text"
                  placeholder="Type here"
                  className="input input-bordered w-full "
                />
                <label className="label">
                </label>
              </div>
              <div className="form-control w-auto px-4">
                <label className="label">
                  <span className="label-text">What is your name?</span>
                </label>
                <input
                  type="text"
                  placeholder="Type here"
                  className="input input-bordered  w-full "
                />
                <label className="label">
                </label>
              </div>
              <div className=" flex items-center justify-center gap-x-6">
                <button className="btn btn-primary">Button</button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
